function Logo() {
  return (
    <div className="text-center">
      <svg
        viewBox="0 0 80 80"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        className="h-24 w-auto mx-auto"
      >
        <rect
          x="10"
          y="30"
          width="60"
          height="44"
          rx="3"
          fill="currentColor"
          className="text-brand-600"
          opacity="0.15"
        />
        <rect
          x="10"
          y="30"
          width="60"
          height="44"
          rx="3"
          stroke="currentColor"
          className="text-brand-600"
          strokeWidth="2"
        />
        <path
          d="M4 32 Q40 14 76 32"
          stroke="currentColor"
          className="text-brand-500"
          strokeWidth="2.5"
          strokeLinecap="round"
          fill="none"
        />
        <rect
          x="18"
          y="40"
          width="10"
          height="8"
          rx="1.5"
          fill="currentColor"
          className="text-brand-500"
          opacity="0.7"
        />
        <rect
          x="35"
          y="40"
          width="10"
          height="8"
          rx="1.5"
          fill="currentColor"
          className="text-brand-500"
          opacity="0.7"
        />
        <rect
          x="52"
          y="40"
          width="10"
          height="8"
          rx="1.5"
          fill="currentColor"
          className="text-brand-500"
          opacity="0.7"
        />
        <rect
          x="18"
          y="54"
          width="10"
          height="8"
          rx="1.5"
          fill="currentColor"
          className="text-brand-400"
          opacity="0.5"
        />
        <rect
          x="52"
          y="54"
          width="10"
          height="8"
          rx="1.5"
          fill="currentColor"
          className="text-brand-400"
          opacity="0.5"
        />
        <rect
          x="33"
          y="58"
          width="14"
          height="16"
          rx="2"
          fill="currentColor"
          className="text-brand-600"
          opacity="0.8"
        />
        <circle
          cx="40"
          cy="22"
          r="4"
          fill="currentColor"
          className="text-brand-500"
          opacity="0.8"
        />
      </svg>
      <div className="text-[1.5rem] font-bold text-brand-500 tracking-wide mt-2">
        HORIZON STAY
      </div>
    </div>
  );
}

export default Logo;
